SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `v_eptable`;
CREATE TABLE `v_eptable` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cgi` varchar(30) DEFAULT NULL,
  `eci` varchar(30) DEFAULT NULL,
  `enodebid` varchar(30) DEFAULT NULL,
  `enodebname` varchar(100) DEFAULT NULL,
  `cellname` varchar(100) DEFAULT NULL,
  `tac` varchar(30) DEFAULT NULL,
  `localcellid` varchar(30) DEFAULT NULL,
  `enbid` varchar(30) DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `coveragetype` varchar(30) DEFAULT NULL,
  `azimuth` double DEFAULT NULL,
  `antennaheight` double DEFAULT NULL,
  `totaldowntiltangle` double DEFAULT NULL,
  `carrierffrequencynum` int(11) DEFAULT NULL,
  `workfrequencyband` varchar(30) DEFAULT NULL,
  `pci` varchar(30) DEFAULT NULL,
  `maxtransmitpower` double DEFAULT NULL,
  `coverscene` varchar(30) DEFAULT NULL,
  `provincename` varchar(30) DEFAULT NULL,
  `cityname` varchar(100) DEFAULT NULL,
  `districtandcounty` varchar(30) DEFAULT NULL,
  `vendor` varchar(30) DEFAULT NULL,
  `electronictiltangle` double DEFAULT NULL,
  `mechanicaltiltangle` double DEFAULT NULL,
  `iscorearea` tinyint(1) DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cgiindex` (`cgi`) USING BTREE,
  KEY `idx_provincename` (`provincename`),
  KEY `idx_cityname` (`cityname`),
  KEY `idx_coverscene` (`coverscene`),
  KEY `idx_vendor` (`vendor`),
  KEY `idx_eci` (`eci`)
) ENGINE=MyISAM AUTO_INCREMENT=5646671 DEFAULT CHARSET=utf8;

